# d2 --sketch HERO.d2 packages/pages/src/assets/hero.svg
Web Page -> Analyze Content: {style.animated: true}

Analyze Content -> Augment Content: {style.animated: true}

Augment Content -> Web Page: {style.animated: true}

Web Page.shape: page
