# Copyright 2025 Mention Ads. All rights reserved.
# Use of this source code is governed by the PolyForm Shield 1.0.0 license
# that can be found in the LICENSE.md file at the root of this repository.

# d2 --sketch --theme=0   HERO.d2 packages/pages/src/assets/hero.light.svg
# d2 --sketch --theme=200 HERO.d2 packages/pages/src/assets/hero.dark.svg
# svgo packages/pages/src/assets/hero.light.svg packages/pages/src/assets/hero.dark.svg

Web Page -> Mention Ads: {style.animated: true}

Mention Ads -> Affiliate Links: {style.animated: true}

Affiliate Links -> Web Page: {style.animated: true}

Web Page.shape: page
