# Copyright 2025 Mentionlink. All rights reserved.
# Use of this source code is governed by the PolyForm Shield 1.0.0 license
# that can be found in the LICENSE.md file at the root of this repository.

# d2 --sketch --theme=0   HERO.d2 packages/docs/src/assets/hero.light.svg
# d2 --sketch --theme=200 HERO.d2 packages/docs/src/assets/hero.dark.svg
# svgo packages/docs/src/assets/hero.light.svg packages/docs/src/assets/hero.dark.svg

Render Web Page.shape: page
Render Web Page -> Detect Product Mentions: {style.animated: true}
Detect Product Mentions -> Insert Affiliate Links: {style.animated: true}
Insert Affiliate Links -> Render Web Page: {style.animated: true}
